# Generated by Django 5.2.4 on 2025-10-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_member",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user is a Fit Six member eligible for discounts.",
            ),
        ),
    ]
