# Generated by Django 5.2.4 on 2025-10-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_remove_product_colour_remove_product_has_sizes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="image_back",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
