# Generated by Django 5.2.4 on 2025-10-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_auto_20251012_1137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=254, unique=True
            ),
        ),
    ]
