# Generated by Django 5.2.4 on 2025-10-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_auto_20251012_1151"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="image_back",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
